[project]
name = "bruggeman"
description = "Repository for the Bruggeman equations from Analytical Solutions of Geohydrological Problems (1999)"
readme = "README.md"
authors = [{ name = "Davíd Brakenhoff", email = "d.brakenhoff@artesia-water.nl" }]
requires-python = ">=3.12"
dependencies = ["numpy", "scipy", "mpmath"]
dynamic = ["version"]

[project.scripts]
bruggeman = "bruggeman:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "bruggeman/__version__.py"

[tool.hatch.metadata]
allow-direct-references = true

[project.optional-dependencies]
sympy = ["sympy"]
ci = ["pytest", "pytest-cov", "nbformat", "nbconvert", "mypy", "ruff"]
docs = [
    "matplotlib",
    "bruggeman[sympy]",
    "Ipython",
    "ipykernel",
    "pydata-sphinx-theme",
    "sphinx",
    "sphinxcontrib-bibtex",
    "numpydoc",
    "sphinx-autoapi",
    "sphinx-design",
    "myst_nb",
    "timflow",
]
dev = ["bruggeman[ci,docs]"]

[tool.ruff]
extend-include = ["*.ipynb"]
lint.extend-select = ["I"]
show-fixes = true
fix = true

[tool.pytest.ini_options]
addopts = "--strict-markers --durations=0"
markers = ["notebooks: run notebooks"]

[tool.mypy]
mypy_path = "bruggeman"

[[tool.mypy.overrides]]
module = ["scipy.special.*", "sympy.*", "mpmath.*"]
ignore_missing_imports = true
